export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const IS_LOADING_REQUEST = 'IS_LOADING_REQUEST';
export const IS_LOADING_SUCCESS = 'IS_LOADING_SUCCESS';
export const IS_LOADING_FAILURE = 'IS_LOADING_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const AXIOS_ERRORS_HANDLER_REQUEST = 'AXIOS_ERRORS_HANDLER_REQUEST';

export const PERSIST_REHIDRATE = 'persist/REHYDRATE';
